name: photo_machine
description: An app to enjoy unlimited photos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  sizer: ^2.0.13
  device_preview: ^0.7.1
  http: ^0.13.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
